version: 0.2
phases:
    pre_build:
        commands:
            # install dependencies... started 'date'
    build:
        commands:
            # tests
            - echo Testing...
artifacts:
    files:
      #- index.html
      #- node_modules/**/*
      - "**/*"
    # discard-paths: no
    base-directory: '/'
