version: 0.2


phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            # install node 14
            - echo n8-n0d3
            - echo install node...
            - curl -sL https://deb.nodesource.com/setup_14.x | bash
            - apt install -y nodejs
            # install mongo
            - echo installing mongo
            - apt install -y mongo
            - yum install -y mongodb-org
            # misc install 
            - apt install --no-install-recommends yarn
    pre_build:
        commands:
            # install dependencies... started 'date'
            - npm install
            - yarn
            #process reload
            - systemctl	daemon-reload
            - #start mongodb process
            - systemctl	start mongod
            - systemctl	enable mongod
    build:
        commands:
            #	tests
            - echo Testing...
            - yarn test
            - echo Building...
            - yarn build
artifacts
    files:
        - index.html
        - node_modules/**/*
        - "**/*"
    # discard-paths: no
    base-directory: '/var/www/html/'

