version: 0.2
phases:
    pre_build:
        commands:
            # install dependencies... started 'date'
    build:
        commands:
            # tests
            - echo Testing...
artifacts:
  type: zip
  files:
    - index.html
