version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
        # installing nodeJS...
        - npm install
artifacts:
  type: zip
  files:
    - index.html
    - "**/*"